# Generated by Django 5.1.4 on 2024-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0002_onlineclassroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
