# Generated by Django 5.1.4 on 2024-12-15 15:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_session'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
