# Generated by Django 5.1.4 on 2024-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_staffs_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
