# Generated by Django 5.1.4 on 2024-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_remove_customuser_gender_remove_staffs_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
